#import "iCore.h"
#import "iJSON.h"
#import "xCustomListView.h"
@class b4i_main;
@class b4i_b4xpages;
@class b4i_b4xcollections;
@class b4i_b4xmainpage;
@class b4i_asdraggablebottomcard;
@class b4i_b4xbitset;
@class b4i_b4xbytesbuilder;
@class _b4xcacheitem;
@class b4i_b4xcache;
@class b4i_b4xcomparatorsort;
@class b4i_b4xorderedmap;
@class b4i_b4xset;
@class b4i_b4xpagesdelegator;
@class _b4xpageparent;
@class _b4xpageinfo;
@class b4i_b4xpagesmanager;
@interface b4i_as_bottomemojipicker : B4IClass
{
@public NSString* __meventname;
@public NSObject* __mcallback;
@public B4IXUI* __xui;
@public NSObject* __tag;
@public B4XViewWrapper* __xparent;
@public b4i_asdraggablebottomcard* __bottomcard;
@public B4XViewWrapper* __xpnl_listviewbackground;
@public b4i_customlistview* __xclv_main;
@public B4XViewWrapper* __xpnl_header;
@public B4XViewWrapper* __xpnl_body;
@public B4XViewWrapper* __xpnl_dragindicator;
@public float __m_headerheight;
@public float __m_bodyheight;
@public int __m_headercolor;
@public int __m_bodycolor;
@public int __m_categorytextcolor;
@public int __m_categoryindicatorcolor;
@public int __m_emojisize;
@public int __m_rows;
@public B4IMap* __m_emojis;
@public B4XViewWrapper* __xpnl_categoriesbackground;
@public B4XViewWrapper* __xpnl_currentcategoryindicator;
@public NSString* __currentcategory;
@public b4i_main* __main;
@public b4i_b4xpages* __b4xpages;
@public b4i_b4xcollections* __b4xcollections;

}- (NSString*)  _class_globals;
@property (nonatomic)NSString* _meventname;
@property (nonatomic)NSObject* _mcallback;
@property (nonatomic)B4IXUI* _xui;
@property (nonatomic)NSObject* _tag;
@property (nonatomic)B4XViewWrapper* _xparent;
@property (nonatomic)b4i_asdraggablebottomcard* _bottomcard;
@property (nonatomic)B4XViewWrapper* _xpnl_listviewbackground;
@property (nonatomic)b4i_customlistview* _xclv_main;
@property (nonatomic)B4XViewWrapper* _xpnl_header;
@property (nonatomic)B4XViewWrapper* _xpnl_body;
@property (nonatomic)B4XViewWrapper* _xpnl_dragindicator;
@property (nonatomic)float _m_headerheight;
@property (nonatomic)float _m_bodyheight;
@property (nonatomic)int _m_headercolor;
@property (nonatomic)int _m_bodycolor;
@property (nonatomic)int _m_categorytextcolor;
@property (nonatomic)int _m_categoryindicatorcolor;
@property (nonatomic)int _m_emojisize;
@property (nonatomic)int _m_rows;
@property (nonatomic)B4IMap* _m_emojis;
@property (nonatomic)B4XViewWrapper* _xpnl_categoriesbackground;
@property (nonatomic)B4XViewWrapper* _xpnl_currentcategoryindicator;
@property (nonatomic)NSString* _currentcategory;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_b4xpages* _b4xpages;
@property (nonatomic)b4i_b4xcollections* _b4xcollections;
- (NSString*)  _createcategories:(B4IArray*) _categorynames :(NSString*) _icon;
- (B4XViewWrapper*)  _createcategoryitem:(NSString*) _text :(B4XFont*) _xfont :(NSObject*) _value;
- (B4XViewWrapper*)  _createlabel:(NSString*) _eventname;
- (NSString*)  _emojiselected:(NSString*) _text;
- (B4IArray*)  _getargb:(int) _color;
- (int)  _getbackgroundcolor;
- (float)  _getbodyheight;
- (int)  _getcategoryindicatorcolor;
- (int)  _getcategorytextcolor;
- (int)  _getemojisize;
- (int)  _getrows;
- (NSString*)  _ini_xclv;
- (NSString*)  _initialize:(B4I*) _ba :(NSObject*) _callback :(NSString*) _eventname :(B4XViewWrapper*) _parent;
- (NSString*)  _setbackgroundcolor:(int) _color;
- (NSString*)  _setbodyheight:(float) _height;
- (NSString*)  _setcategoryindicatorcolor:(int) _color;
- (NSString*)  _setcategorytextcolor:(int) _color;
- (NSString*)  _setemojisize:(int) _size;
- (NSString*)  _setrows:(int) _rows;
- (void)  _showpicker;
- (NSString*)  _xclv_main_visiblerangechanged:(int) _firstindex :(int) _lastindex;
- (NSString*)  _xlbl_category_click;
- (NSString*)  _xlbl_emoji_click;
@end
