#import "iCore.h"
#import "iJSON.h"
#import "xCustomListView.h"
@class b4i_main;
@class b4i_b4xpages;
@class b4i_b4xcollections;
@class b4i_b4xmainpage;
@class b4i_as_bottomemojipicker;
@class b4i_b4xbitset;
@class b4i_b4xbytesbuilder;
@class _b4xcacheitem;
@class b4i_b4xcache;
@class b4i_b4xcomparatorsort;
@class b4i_b4xorderedmap;
@class b4i_b4xset;
@class b4i_b4xpagesdelegator;
@class _b4xpageparent;
@class _b4xpageinfo;
@class b4i_b4xpagesmanager;
@interface b4i_asdraggablebottomcard : B4IClass
{
@public NSString* __meventname;
@public NSObject* __mcallback;
@public B4IXUI* __xui;
@public B4XViewWrapper* __mdarkpanel;
@public float __downy;
@public float __old_top;
@public float __g_first_height;
@public float __g_second_height;
@public float __g_width;
@public float __g_header_height;
@public int __g_orientation;
@public int __g_show_duration;
@public int __g_hide_duration;
@public int __g_darkpanel_alpha;
@public BOOL __g_isdraggable;
@public BOOL __mdarkpanelclickable;
@public BOOL __musercanclose;
@public BOOL __m_bodydrag;
@public int __expand_state;
@public BOOL __disable_touch;
@public BOOL __last_swipe2top;
@public BOOL __inclosingprocess;
@public B4XViewWrapper* __xpnl_cardbase;
@public B4XViewWrapper* __xpnl_cardheader;
@public B4XViewWrapper* __xpnl_cardbody;
@public B4INativeObject* __nome;
@public B4IViewWrapper* __mview;
@public B4IViewWrapper* __mview2;
@public b4i_main* __main;
@public b4i_b4xpages* __b4xpages;
@public b4i_b4xcollections* __b4xcollections;

}- (NSString*)  _addpangesture:(int) _minimumtouch :(int) _maximumtouch;
- (NSString*)  _base_resize:(double) _width :(double) _height;
- (NSString*)  _class_globals;
@property (nonatomic)NSString* _meventname;
@property (nonatomic)NSObject* _mcallback;
@property (nonatomic)B4IXUI* _xui;
@property (nonatomic)B4XViewWrapper* _mdarkpanel;
@property (nonatomic)float _downy;
@property (nonatomic)float _old_top;
@property (nonatomic)float _g_first_height;
@property (nonatomic)float _g_second_height;
@property (nonatomic)float _g_width;
@property (nonatomic)float _g_header_height;
@property (nonatomic)int _g_orientation;
@property (nonatomic)int _g_show_duration;
@property (nonatomic)int _g_hide_duration;
@property (nonatomic)int _g_darkpanel_alpha;
@property (nonatomic)BOOL _g_isdraggable;
@property (nonatomic)BOOL _mdarkpanelclickable;
@property (nonatomic)BOOL _musercanclose;
@property (nonatomic)BOOL _m_bodydrag;
@property (nonatomic)int _expand_state;
@property (nonatomic)BOOL _disable_touch;
@property (nonatomic)BOOL _last_swipe2top;
@property (nonatomic)BOOL _inclosingprocess;
@property (nonatomic)B4XViewWrapper* _xpnl_cardbase;
@property (nonatomic)B4XViewWrapper* _xpnl_cardheader;
@property (nonatomic)B4XViewWrapper* _xpnl_cardbody;
@property (nonatomic)B4INativeObject* _nome;
@property (nonatomic)B4IViewWrapper* _mview;
@property (nonatomic)B4IViewWrapper* _mview2;
@property (nonatomic)b4i_main* _main;
@property (nonatomic)b4i_b4xpages* _b4xpages;
@property (nonatomic)b4i_b4xcollections* _b4xcollections;
- (NSString*)  _create:(B4XViewWrapper*) _parent :(float) _first_height :(float) _second_height :(float) _header_height :(float) _width :(int) _orientation;
- (NSString*)  _expandfull;
- (NSString*)  _expandhalf;
- (BOOL)  _getbodydrag;
- (B4XViewWrapper*)  _getbodypanel;
- (B4XViewWrapper*)  _getcardbase;
- (B4XViewWrapper*)  _getdarkpanel;
- (int)  _getdarkpanelalpha;
- (BOOL)  _getdarkpanelclickable;
- (float)  _getfirstheight;
- (float)  _getheaderheight;
- (B4XViewWrapper*)  _getheaderpanel;
- (BOOL)  _getisdraggable;
- (BOOL)  _getisopen;
- (BOOL)  _getisopenfull;
- (BOOL)  _getisopenhalf;
- (float)  _getsecondheight;
- (BOOL)  _getusercanclose;
- (BOOL)  _handletouch:(int) _action :(float) _y;
- (void)  _hide:(BOOL) _ignore_event;
- (NSString*)  _ini_views:(B4XViewWrapper*) _parent;
- (NSString*)  _initialize:(B4I*) _ba :(NSObject*) _callback :(NSString*) _eventname;
- (NSString*)  _mdarkpanel_click;
- (int)  _orientation_left;
- (int)  _orientation_middle;
- (int)  _orientation_right;
- (NSString*)  _setbodydrag:(BOOL) _enabled;
- (NSString*)  _setbodypanel:(B4XViewWrapper*) _bodypanel;
- (NSString*)  _setcircleclip:(B4XViewWrapper*) _pnl :(int) _radius;
- (NSString*)  _setcornerradius_header:(float) _radius;
- (NSString*)  _setdarkpanelalpha:(int) _alpha;
- (NSString*)  _setdarkpanelclickable:(BOOL) _clickable;
- (NSString*)  _setfirstheight:(float) _height;
- (NSString*)  _setheaderpanel:(B4XViewWrapper*) _headerpanel;
- (NSString*)  _setisdraggable:(BOOL) _draggable;
- (NSString*)  _setsecondheight:(float) _height;
- (NSString*)  _setusercanclose:(BOOL) _canclose;
- (NSString*)  _show:(BOOL) _ignore_event;
- (void)  _showintern:(BOOL) _ignore_event :(BOOL) _fromtouch;
- (NSString*)  _uigesture_pan:(int) _state :(float) _x :(float) _y :(NSObject*) _obj;
- (NSString*)  _visiblebodyheightchanged;
@end
